### ISSUE TITLE
Serial needed

### ISSUE THREAD

**Issue by svonfeltenDev** [Seeed-Studio/Seeed_Arduino_Mic#3]
Is this normal behaviour that serial connexion is needed ?

**Comment by Pillar1989** [comment]
@lakshanthad  any idea?

**Comment by lakshanthad** [comment]
Hello @svonfeltenDev,

Could you please tell me which hardware you are trying to use with this library?

Also, please explain more about your problem.

Thank you.

**Comment by svonfeltenDev** [comment]
Hello, I use the xiao nrf52840 sense and when I disconnect the USB Cable from the Xiao values are freaking out. The same thing with the gyroscope on the board. Is it a material problem or from the code ?

**Comment by lakshanthad** [comment]
Hello,

I am not sure why you are trying to disconnect the board. Once you disconnect, there will be no serial output.

**Comment by svonfeltenDev** [comment]
I use the data to display LEDs colors and not to plot this on serial, there is no serial connected

**Comment by Cincinnatu** [comment]
> 我使用数据来显示 LED 颜色，而不是在串行上绘制它，没有串行连接

Could you provide some more detailed description of the issue?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
