### ISSUE TITLE
Loop audio, longer audio archive

### ISSUE THREAD

**Issue by josewapepewa** [Seeed-Studio/Seeed_Arduino_Mic#4]
How can I modify the recorded audio to last longer?
And how can I make it loop the audio?
The project that I want to do is to activate by bluettoh so that it starts recording and I'm a bit lost.
First I wanted to make it record several audios and later do the thing of activating by bluetooth.
Thanks.

**Comment by Cincinnatu** [comment]
> How can I modify the recorded audio to last longer? And how can I make it loop the audio? The project that I want to do is to activate by bluettoh so that it starts recording and I'm a bit lost. First I wanted to make it record several audios and later do the thing of activating by bluetooth. Thanks.

You can increase the duration of the recording briefly by modifying the value of SAMPLES in the process, but not for too long, as the routine uses an array to store the data, which would exceed the size of RAM if it's too long.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
