### ISSUE TITLE
Mic serial plotter shows errors

### ISSUE THREAD

**Issue by luvwinnie** [Seeed-Studio/Seeed_Arduino_Mic#5]
I tried to upload the [mic_serial_plotter.ino](https://github.com/Seeed-Studio/Seeed_Arduino_Mic/blob/master/examples/mic_serial_plotter/mic_serial_plotter.ino) to nRF52840 BLE Sense without Seeeduino XIAO Expansion board. However, it shows the following error on macOS.

```
 #error "This library targets only Wio Terminal boards at the moment"
  ^~~~~
exit status 1
Error compiling for board Seeed XIAO BLE Sense - nRF52840.

```

How can I solve this?

**Comment by omidz97** [comment]
> I tried to upload the [mic_serial_plotter.ino](https://github.com/Seeed-Studio/Seeed_Arduino_Mic/blob/master/examples/mic_serial_plotter/mic_serial_plotter.ino) to nRF52840 BLE Sense without Seeeduino XIAO Expansion board. However, it shows the following error on macOS.
> 
> ```
>  #error "This library targets only Wio Terminal boards at the moment"
>   ^~~~~
> exit status 1
> Error compiling for board Seeed XIAO BLE Sense - nRF52840.
> ```
> 
> How can I solve this?

**You must select "Seeed XIAO BLE Sense - nRF52840" board from the tools menu.
Go to Tools > Board > Select "Seeed XIAO BLE Sense - nRF52840" option .**

 If you don't see this option, first you must install the board package:
To navigate to File > Preferences, and fill “Additional Boards Manager URLs” with the URL below:
_https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json_
Navigate to Tools > Board > Boards Manager, type the keyword “seeed nrf52” in the search box, select the latest version of Seeed nRF52 Boards, and install it.
After installing the board package, navigate to Tools > Board > Seeed nRF Boards and select “Seeed XIAO BLE – nRF52840“.

Now you should be able to compile correctly.

**Comment by street-grease-coder** [comment]
I have the same issue with the correct board selected...

**Comment by vkfive** [comment]
I also have the same issue, correct board selected as well, the only difference it is listed as "Seeed XIAO nRF52840 Sense" and not as "Seeed XIAO BLE Sense - nRF52840" as it is mentioned in the response above, if it makes any difference. How do I resolve it?

**Comment by bigbearishappy** [comment]
This demo code of nrf52840 is based on mbed os. So when we select the board, we should select it under `Seeed nRF 52 mbed-enabled Boards`.

Tools->Board->Seeed nRF 52 mbed-enabled Boards->...

Then it should be able to compile.

**Comment by Cincinnatu** [comment]
> I tried to upload the [mic_serial_plotter.ino](https://github.com/Seeed-Studio/Seeed_Arduino_Mic/blob/master/examples/mic_serial_plotter/mic_serial_plotter.ino) to nRF52840 BLE Sense without Seeeduino XIAO Expansion board. However, it shows the following error on macOS.
> 
> ```
>  #error "This library targets only Wio Terminal boards at the moment"
>   ^~~~~
> exit status 1
> Error compiling for board Seeed XIAO BLE Sense - nRF52840.
> ```
> 
> How can I solve this?

Have you tried the suggestion in this GitHub comment https://github.com/Seeed-Studio/Seeed_Arduino_Mic/issues/5#issuecomment-2290380486, and does it work properly?

**Comment by vkfive** [comment]
I've resolved it by using different library Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: CIncinnatus ***@***.***> Date: 10/16/24  8:34 AM  (GMT+07:00) To: Seeed-Studio/Seeed_Arduino_Mic ***@***.***> Cc: vkfive ***@***.***>, Comment ***@***.***> Subject: Re: [Seeed-Studio/Seeed_Arduino_Mic] Mic serial plotter shows errors (Issue #5) 

I tried to upload the mic_serial_plotter.ino to nRF52840 BLE Sense without Seeeduino XIAO Expansion board. However, it shows the following error on macOS.
 #error "This library targets only Wio Terminal boards at the moment"
  ^~~~~
exit status 1
Error compiling for board Seeed XIAO BLE Sense - nRF52840.

How can I solve this?

Have you tried the suggestion in this GitHub comment #5 (comment), and does it work properly?

**Comment by Cincinnatu** [comment]
"The error message '#error "This library targets only Wio Terminal boards at the moment"' occurs because the Seeed_Arduino_Mic library file does not yet support the XIAO nRF52840 BLE Sense version. Therefore, you need to reinstall this library file, make sure it is the latest version, in order to use XIAO nRF52840 BLE Sense properly."
