### ISSUE TITLE
Why can't I change the sampling rate?

### ISSUE THREAD

**Issue by HemanthSabbella** [Seeed-Studio/Seeed_Arduino_Mic#7]
I tried changing the sampling rate in the code, the serial monitor doesn't give any output, it's the same for any other sampling rate than 16kHz. Can someone explain why?

**Comment by Cincinnatu** [comment]
> I tried changing the sampling rate in the code, the serial monitor doesn't give any output, it's the same for any other sampling rate than 16kHz. Can someone explain why?

The sampling frequency in this library contains two options: a higher one at 16kHz and a lower one at 8kHz. Any other frequency configurations are incorrect and will result in abnormal operation.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
