### ISSUE TITLE
Arduino IDE will not compile 

### ISSUE THREAD

**Issue by savall21** [Seeed-Studio/Seeed_Arduino_Mic#8]
I have Seeed Xiao nRF52840 Sense selected as my board. I have the Seeed_Arduino_Mic library installed. When I try to compile the examples I get the following error:

In file included from /private/var/folders/8_/1915b5lx1xj1nqpz1hdzk1pm0000gn/T/.arduinoIDE-unsaved2023721-9360-q7t36m.gn1m/mic_serial_plotter/mic_serial_plotter.ino:1:
/Users/christhopercarpenter/Documents/Arduino/libraries/Seeed_Arduino_Mic/src/mic.h:25:2: error: #error "This library targets only Wio Terminal boards at the moment"
   25 | #error "This library targets only Wio Terminal boards at the moment"
      |  ^~~~~

exit status 1

Compilation error: exit status 1

I'm running the latest version of IDE 2.1.1

**Comment by savall21** [comment]
Nevermind, wrong board.

**Comment by dustinkerstein** [comment]
@savall21 how were you able to get this running on a Seeed Xiao nRF52840 Sense? I am running into that same error when I upload the mic_serial_plotter sketch using the Seeed nrf52 mbed-enabled Boards and Seeed nrf52 Boards libraries.

**Comment by felyu** [comment]
hey! I have the same issue as you @dustinkerstein, did you manage to solve it ? Tysm
